# Data Preparation
## Importance
According to a survey in Forbes, data scientists spend 80% of their time on data preparation
![Pie Chart](https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fgilpress%2Ffiles%2F2016%2F03%2FTime-1200x511.jpg)
Let's try different approaches and observe their effects on models, and finally choose the best one. Eventually : garbage in, garbage out.

In [280]:
import numpy as np
import category_encoders as ce        # for encoding of categorical features
import pandas as pd

# Import Test set

In [281]:
df_test = pd.read_csv("data/test.csv", index_col="Id",
                      keep_default_na=False)   # keep_default_na is preventing "NA" to become NaN object 
                                            # try keep_default_na=True to see the difference
    
sample_sub = pd.read_csv("data/sample_submission.csv", index_col="Id", keep_default_na=False)
df_full_test = df_test.join(sample_sub)
    
df_full_test

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80,11622,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,MnPrv,NA,0,6,2010,WD,Normal,169277.052498
1462,20,RL,81,14267,Pave,NA,IR1,Lvl,AllPub,Corner,...,0,NA,NA,Gar2,12500,6,2010,WD,Normal,187758.393989
1463,60,RL,74,13830,Pave,NA,IR1,Lvl,AllPub,Inside,...,0,NA,MnPrv,NA,0,3,2010,WD,Normal,183583.683570
1464,60,RL,78,9978,Pave,NA,IR1,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,6,2010,WD,Normal,179317.477511
1465,120,RL,43,5005,Pave,NA,IR1,HLS,AllPub,Inside,...,0,NA,NA,NA,0,1,2010,WD,Normal,150730.079977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21,1936,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,6,2006,WD,Normal,167081.220949
2916,160,RM,21,1894,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,4,2006,WD,Abnorml,164788.778231
2917,20,RL,160,20000,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,9,2006,WD,Abnorml,219222.423400
2918,85,RL,62,10441,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,MnPrv,Shed,700,7,2006,WD,Normal,184924.279659
2919,60,RL,74,9627,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,11,2006,WD,Normal,187741.866657

## Display Number of NaN values :

In [282]:
df_test.isna().sum().sum()

0

# Import Train set

In [283]:
df_train = pd.read_csv("data/train.csv", index_col="Id", keep_default_na=False)
df_train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65,8450,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,2,2008,WD,Normal,208500
2,20,RL,80,9600,Pave,NA,Reg,Lvl,AllPub,FR2,...,0,NA,NA,NA,0,5,2007,WD,Normal,181500
3,60,RL,68,11250,Pave,NA,IR1,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,9,2008,WD,Normal,223500
4,70,RL,60,9550,Pave,NA,IR1,Lvl,AllPub,Corner,...,0,NA,NA,NA,0,2,2006,WD,Abnorml,140000
5,60,RL,84,14260,Pave,NA,IR1,Lvl,AllPub,FR2,...,0,NA,NA,NA,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62,7917,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,8,2007,WD,Normal,175000
1457,20,RL,85,13175,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,MnPrv,NA,0,2,2010,WD,Normal,210000
1458,70,RL,66,9042,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68,9717,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,4,2010,WD,Normal,142125
1460,20,RL,75,9937,Pave,NA,Reg,Lvl,AllPub,Inside,...,0,NA,NA,NA,0,6,2008,WD,Normal,147500

## Number of NaNs in train set

In [284]:
df_train.isna().sum().sum()

0

# Feature Engineering
## Feature Selection
Removing useless columns

## Looking at correlations between features and target variable (SalePrice)

In [285]:
df_train[df_train.columns].corr(method="pearson")["SalePrice"][:]

MSSubClass      -0.084284
LotArea          0.263843
OverallQual      0.790982
OverallCond     -0.077856
YearBuilt        0.522897
YearRemodAdd     0.507101
BsmtFinSF1       0.386420
BsmtFinSF2      -0.011378
BsmtUnfSF        0.214479
TotalBsmtSF      0.613581
1stFlrSF         0.605852
2ndFlrSF         0.319334
LowQualFinSF    -0.025606
GrLivArea        0.708624
BsmtFullBath     0.227122
BsmtHalfBath    -0.016844
FullBath         0.560664
HalfBath         0.284108
BedroomAbvGr     0.168213
KitchenAbvGr    -0.135907
TotRmsAbvGrd     0.533723
Fireplaces       0.466929
GarageCars       0.640409
GarageArea       0.623431
WoodDeckSF       0.324413
OpenPorchSF      0.315856
EnclosedPorch   -0.128578
3SsnPorch        0.044584
ScreenPorch      0.111447
PoolArea         0.092404
MiscVal         -0.021190
MoSold           0.046432
YrSold          -0.028923
SalePrice        1.000000
Name: SalePrice, dtype: float64

In [286]:
columns_to_drop = []    # we will add cols in there and drop all of them in the end of the Feature Selection
                        # instead of dropping one by one using many cells
df_train.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [287]:
df_train["MSSubClass"].value_counts(normalize=True)*100   # show percent of category values

20     36.712329
60     20.479452
50      9.863014
120     5.958904
30      4.726027
160     4.315068
70      4.109589
80      3.972603
90      3.561644
190     2.054795
85      1.369863
75      1.095890
45      0.821918
180     0.684932
40      0.273973
Name: MSSubClass, dtype: float64

In [288]:
df_train["MSZoning"].value_counts(normalize=True)*100

RL         78.835616
RM         14.931507
FV          4.452055
RH          1.095890
C (all)     0.684932
Name: MSZoning, dtype: float64

In [289]:
df_train["Street"].value_counts(normalize=True)*100

Pave    99.589041
Grvl     0.410959
Name: Street, dtype: float64

### "Street" feature
99% are Pave, so it is useless column. Let's drop it and all other features, in which one value is encountered in more than 80% of cases

In [290]:
for col in df_train.columns:
    if (df_train[col].value_counts(normalize=True)*100).iloc[0] >= 80:
        columns_to_drop.append(col)
        print(col)
        
df_train.drop(columns=columns_to_drop, inplace=True)
df_full_test.drop(columns=columns_to_drop, inplace=True)

Street
Alley
LandContour
Utilities
LandSlope
Condition1
Condition2
BldgType
RoofMatl
ExterCond
BsmtCond
BsmtFinType2
BsmtFinSF2
Heating
CentralAir
Electrical
LowQualFinSF
BsmtHalfBath
KitchenAbvGr
Functional
GarageQual
GarageCond
PavedDrive
EnclosedPorch
3SsnPorch
ScreenPorch
PoolArea
PoolQC
Fence
MiscFeature
MiscVal
SaleType
SaleCondition

## Checking data sets to correctness
### Check for unexpected values in train set

In [291]:
for col in df_train.columns:     # some columns contain unexpected NAs
    if "NA" in df_train[col].unique():
        print(col)

LotFrontage
MasVnrType
MasVnrArea
BsmtQual
BsmtExposure
BsmtFinType1
FireplaceQu
GarageType
GarageYrBlt
GarageFinish

<ipython-input-291-d25d11d9a532>:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if "NA" in df_train[col].unique():

According to data_description.csv NA is allowed in : BsmtQual, BsmtExposure, BsmtFinType1, FireplaceQu, GarageType, GarageFinish, so keep them untouched

In [292]:
df_train["LotFrontage"].unique()

array(['65', '80', '68', '60', '84', '85', '75', 'NA', '51', '50', '70',
       '91', '72', '66', '101', '57', '44', '110', '98', '47', '108',
       '112', '74', '115', '61', '48', '33', '52', '100', '24', '89',
       '63', '76', '81', '95', '69', '21', '32', '78', '121', '122', '40',
       '105', '73', '77', '64', '94', '34', '90', '55', '88', '82', '71',
       '120', '107', '92', '134', '62', '86', '141', '97', '54', '41',
       '79', '174', '99', '67', '83', '43', '103', '93', '30', '129',
       '140', '35', '37', '118', '87', '116', '150', '111', '49', '96',
       '59', '36', '56', '102', '58', '38', '109', '130', '53', '137',
       '45', '106', '104', '42', '39', '144', '114', '128', '149', '313',
       '168', '182', '138', '160', '152', '124', '153', '46'],
      dtype=object)

In [293]:
df_train["LotFrontage"].value_counts()       # too many NA, let's drop column

NA     259
60     143
70      70
80      69
50      57
      ...
137      1
38       1
33       1
150      1
46       1
Name: LotFrontage, Length: 111, dtype: int64

In [294]:
df_train.drop(columns=["LotFrontage",], inplace=True)
df_full_test.drop(columns=["LotFrontage",], inplace=True)

In [295]:
df_train["MasVnrType"].unique()

array(['BrkFace', 'None', 'Stone', 'BrkCmn', 'NA'], dtype=object)

In [296]:
df_train["MasVnrType"].value_counts()    # not so many NA, let's remove rows with NA

None       864
BrkFace    445
Stone      128
BrkCmn      15
NA           8
Name: MasVnrType, dtype: int64

In [297]:
df_train = df_train[df_train["MasVnrType"] != "NA"]
df_train["MasVnrType"].unique()    # cleared from NA

array(['BrkFace', 'None', 'Stone', 'BrkCmn'], dtype=object)

In [298]:
"NA" in df_train["MasVnrArea"].unique()   # previously deleted MasVnrType also remove MasVnrArea, so no NAs now

False

In [299]:
"NA" in df_train["GarageYrBlt"].unique()

True

In [300]:
df_train["GarageYrBlt"].replace(to_replace="NA", value="0", inplace=True)
"NA" in df_train["GarageYrBlt"].unique()

/home/fah/.local/lib/python3.8/site-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

False

In [301]:
df_train["GarageYrBlt"] = df_train["GarageYrBlt"].astype(int)
df_train["GarageYrBlt"]

<ipython-input-301-b065119a1e7d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train["GarageYrBlt"] = df_train["GarageYrBlt"].astype(int)

Id
1       2003
2       1976
3       2001
4       1998
5       2000
        ...
1456    1999
1457    1978
1458    1941
1459    1950
1460    1965
Name: GarageYrBlt, Length: 1452, dtype: int64

### Check for unexpected values in test set

In [302]:
for col in df_full_test.columns:     # some columns contain unexpected NAs
    if "NA" in df_full_test[col].unique():
        print(col)

MSZoning
Exterior1st
Exterior2nd
MasVnrType
MasVnrArea
BsmtQual
BsmtExposure
BsmtFinType1
BsmtFinSF1
BsmtUnfSF
TotalBsmtSF
BsmtFullBath
KitchenQual
FireplaceQu
GarageType
GarageYrBlt
GarageFinish
GarageCars
GarageArea

<ipython-input-302-25f226bd084d>:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if "NA" in df_full_test[col].unique():

In [303]:
# to do : resolve NAs while encoding, fill with 0, manually

## Encoding
For encoding "category_encoding" lib is used [documentation](https://contrib.scikit-learn.org/category_encoders/)

In [304]:
dummy_train = df_train.replace(to_replace="NA", value=np.nan, inplace=False)    # for one-hot encoding to fill
dummy_test = df_full_test.replace(to_replace="NA", value=np.nan, inplace=False)  # all NAs with 0s

### Creating lists of columns, for which one hot / ordinal encoding would be suitable

In [305]:
one_hot_cols = ["MSZoning", "LotConfig", "Neighborhood", "HouseStyle", "RoofStyle", "Exterior1st",
                "Exterior2nd", "MasVnrType", "Foundation", "GarageType",]

ordinal_cols = ["LotShape", "ExterQual", "BsmtQual", "BsmtExposure", "BsmtFinType1", "HeatingQC",
                "KitchenQual", "FireplaceQu", "GarageFinish",]

mapping = [
    {"col":"LotShape", "mapping":{"IR3":-1, "IR2":0, "NA":0, "IR1":1, "Reg":2}},
    {"col":"ExterQual", "mapping":{"Po":-2, "Fa":-1, "TA":0, "NA":0, "Gd":1, "Ex":2}},
    {"col":"BsmtQual", "mapping":{"NA":-1,"Po":0, "Fa":1, "TA":2, "Gd":3, "Ex":4}},
    {"col":"BsmtExposure", "mapping":{"NA":-1, "No":0, "Mn":1, "Av":2, "Gd":3}},
    {"col":"BsmtFinType1", "mapping":{"NA":-1, "Unf":0, "LwQ":1, "Rec":2, "BLQ":3, "ALQ":4, "GLQ":5}},
    {"col":"HeatingQC", "mapping":{"Po":0, "NA":0, "Fa":1, "TA":2, "Gd":3, "Ex":4}},
    {"col":"KitchenQual", "mapping":{"Po":0, "NA":0, "Fa":1, "TA":2, "Gd":3, "Ex":4}},
    {"col":"FireplaceQu", "mapping":{"NA":-2, "Po":-1, "Fa":0, "TA":1, "Gd":2, "Ex":3}},
    {"col":"GarageFinish", "mapping":{"NA":-1, "Unf":0, "RFn":1, "Fin":2}},
]

one_hot_encoder = ce.OneHotEncoder(cols=one_hot_cols, return_df=True, use_cat_names=True, handle_unknown="value",
                    handle_missing="value").fit(dummy_train.append(other=dummy_test).dropna())

ordinal_encoder = ce.OrdinalEncoder(cols=ordinal_cols, return_df=True, mapping=mapping,
                                   handle_unknown="value", handle_missing="value")

len(one_hot_cols), len(ordinal_cols), len(df_train.columns)

(10, 9, 46)

### Encoding Train set

In [306]:
encoded_train_df = one_hot_encoder.transform(df_train)
encoded_train_df = ordinal_encoder.fit_transform(encoded_train_df)
encoded_train_df

,MSSubClass,MSZoning_RL,MSZoning_RM,MSZoning_C (all),MSZoning_FV,MSZoning_RH,LotArea,LotShape,LotConfig_FR2,LotConfig_Inside,...,GarageType_2Types,GarageYrBlt,GarageFinish,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,MoSold,YrSold,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,1,0,0,0,0,8450,2,0,1,...,0,2003,1,2,548,0,61,2,2008,208500
2,20,1,0,0,0,0,9600,2,1,0,...,0,1976,1,2,460,298,0,5,2007,181500
3,60,1,0,0,0,0,11250,1,0,1,...,0,2001,1,2,608,0,42,9,2008,223500
4,70,1,0,0,0,0,9550,1,0,0,...,0,1998,0,3,642,0,35,2,2006,140000
5,60,1,0,0,0,0,14260,1,1,0,...,0,2000,1,3,836,192,84,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,1,0,0,0,0,7917,2,0,1,...,0,1999,1,2,460,0,40,8,2007,175000
1457,20,1,0,0,0,0,13175,2,0,1,...,0,1978,0,2,500,349,0,2,2010,210000
1458,70,1,0,0,0,0,9042,2,0,1,...,0,1941,1,1,252,0,60,5,2010,266500
1459,20,1,0,0,0,0,9717,2,0,1,...,0,1950,0,1,240,366,0,4,2010,142125
1460,20,1,0,0,0,0,9937,2,0,1,...,0,1965,2,1,276,736,68,6,2008,147500

In [307]:
encoded_train_df.info()   # 1 column is object type (MasVnrArea column)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1452 entries, 1 to 1460
Columns: 127 entries, MSSubClass to SalePrice
dtypes: int64(126), object(1)
memory usage: 1.4+ MB

In [308]:
encoded_train_df = encoded_train_df.astype(int)   # make MasVnrArea int
encoded_train_df.info()    # now it is clear

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1452 entries, 1 to 1460
Columns: 127 entries, MSSubClass to SalePrice
dtypes: int64(127)
memory usage: 1.4 MB

In [309]:
encoded_train_df.isna().sum().sum()

0

### Encoding Test set

In [310]:
encoded_test_df = one_hot_encoder.transform(df_full_test)
encoded_test_df = ordinal_encoder.fit_transform(encoded_test_df)
encoded_test_df.replace(to_replace="NA", value=0, inplace=True)
encoded_test_df

,MSSubClass,MSZoning_RL,MSZoning_RM,MSZoning_C (all),MSZoning_FV,MSZoning_RH,LotArea,LotShape,LotConfig_FR2,LotConfig_Inside,...,GarageType_2Types,GarageYrBlt,GarageFinish,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,MoSold,YrSold,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,0,0,0,0,1,11622,2,0,1,...,0,1961,0,1,730,140,0,6,2010,169277.052498
1462,20,1,0,0,0,0,14267,1,0,0,...,0,1958,0,1,312,393,36,6,2010,187758.393989
1463,60,1,0,0,0,0,13830,1,0,1,...,0,1997,2,2,482,212,34,3,2010,183583.683570
1464,60,1,0,0,0,0,9978,1,0,1,...,0,1998,2,2,470,360,36,6,2010,179317.477511
1465,120,1,0,0,0,0,5005,1,0,1,...,0,1992,1,2,506,0,82,1,2010,150730.079977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,0,1,0,0,0,1936,2,0,1,...,0,0,-1,0,0,0,0,6,2006,167081.220949
2916,160,0,1,0,0,0,1894,2,0,1,...,0,1970,0,1,286,0,24,4,2006,164788.778231
2917,20,1,0,0,0,0,20000,2,0,1,...,0,1960,0,2,576,474,0,9,2006,219222.423400
2918,85,1,0,0,0,0,10441,2,0,1,...,0,0,-1,0,0,80,32,7,2006,184924.279659
2919,60,1,0,0,0,0,9627,2,0,1,...,0,1993,2,3,650,190,48,11,2006,187741.866657

In [311]:
encoded_test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 1461 to 2919
Columns: 127 entries, MSSubClass to SalePrice
dtypes: float64(1), int64(118), object(8)
memory usage: 1.4+ MB

In [312]:
encoded_test_df = encoded_test_df.astype(float)
encoded_test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 1461 to 2919
Columns: 127 entries, MSSubClass to SalePrice
dtypes: float64(127)
memory usage: 1.4 MB

In [313]:
encoded_train_df.to_csv("data/prepared_train.csv")
encoded_test_df.to_csv("data/prepared_test.csv")